name = "nitedu-anomaly-detection"
main = "worker.js"
compatibility_date = "2025-09-20"

[vars]
ANOMALY_API_URL = "https://nitedu-anomaly-detection.onrender.com"

[[routes]]
pattern = "nitedu.in/*"
zone_name = "nitedu.in"

[[routes]]
pattern = "www.nitedu.in/*"
zone_name = "nitedu.in"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



